### ISSUE TITLE
Fails unit tests in node v0.11

### ISSUE THREAD

**Issue by bemson** [bemson/salt#45]
While integrating with [travis-ci.com](https://travis-ci.org/bemson/Flow), it seems Flow can not pass unit tests on node v0.11. This issue should track progress in debugging the core problem. In the interim, the travis-ci config was updated to ignore this environment.

One caveat: It may be that v0.11 is an edge version of NodeJS, since [nodejs.org](http://nodejs.org) lists the current version as 10.5. (The [Mocha](http://http://visionmedia.github.io/mocha/) based tests were augmented to pass there, but those issues involved how the [sinon](http://sinonjs.org/) components were being used.) Thus, this issue has a lower priority.

**Comment by bemson** [comment]
@stigi you're the only node guy I know, who has some understanding of Flow. It's been a year, but not much has changed, besides the quality of the code (for the better, I hope). The unit tests and recently closed issues are your best guidance, in terms of documentation - but again, not much has changed. :-)

If you're interested and have time, do please take a look at how and why these unit tests fail in node v0.11. Also, is my implication that v0.11 is an unstable build true (i.e., within the nodejs community)? Any insights are welcome! I'm busy trying to write that documentation and code some demo stuffs.

Thanks in advance, and no worries if you're unable to participate.

**Comment by stigi** [comment]
@bemson I'm actually not much of a node coder. I was fooling around with the language and libraries but never used it for more than a weekend project (the last one being more than a year in the past).

I'd suggest someone who uses node on a day to day basis, and is familiar with flow should/could have a look.

**Comment by bemson** [comment]
No worries @stigi. Thanks for the prompt reply! :-)

**Comment by bemson** [comment]
Noting that both [Panzer](https://github.com/bemson/panzer) and [genData](http://github.com/bemson/gendata) pass their unit tests on node v0.11. Hopefully this means the problem is isolated to Salt's code base.

**Comment by bemson** [comment]
Not sure what happened, but tests are now passing in v0.11, both locally and on [travis-ci/bemson/salt](https://travis-ci.org/bemson/salt/jobs/18628479).
